#!/bin/bash

# ============================================
# Online Tests Feature - Setup Checklist
# ============================================

echo "🚀 Starting Online Tests Feature Setup..."
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Checklist items
declare -a CHECKLIST=(
  "✅ Backend Controllers: testController.ts"
  "✅ Backend Routes: testRoutes.ts"
  "✅ Database Models: Test.ts and TestAttempt.ts"
  "✅ Server.ts updated with test routes"
  "✅ Frontend Service: testService.ts"
  "✅ Frontend Components: TestCard.tsx"
  "✅ Frontend Components: QuestionCard.tsx"
  "✅ Frontend Pages: StudentTests.tsx"
  "✅ Frontend Pages: TestAttempt.tsx"
  "✅ Frontend Pages: TestResults.tsx"
  "✅ App.tsx routes configured"
)

echo -e "${GREEN}Implementation Checklist:${NC}"
echo "=============================="
for item in "${CHECKLIST[@]}"; do
  echo "$item"
done

echo ""
echo -e "${YELLOW}📋 Quick Start Guide${NC}"
echo "=================="
echo ""

echo "1. 📦 Ensure Dependencies Installed"
echo "   Backend:"
echo "   - mongoose"
echo "   - express"
echo "   - typescript"
echo "   - jsonwebtoken"
echo ""
echo "   Frontend:"
echo "   - react"
echo "   - react-router-dom"
echo "   - axios"
echo "   - lucide-react"
echo "   - tailwindcss"
echo ""

echo "2. 🗄️ Database Setup"
echo "   - MongoDB should be running"
echo "   - Database connection configured in backend/server/config/db.ts"
echo "   - Models automatically created on first run"
echo ""

echo "3. 🔑 Create Test Data"
echo "   Option A: Use seed file (if created)"
echo "   $ npx ts-node backend/seedTests.ts"
echo ""
echo "   Option B: Use MongoDB directly"
echo "   - Insert test documents using Test.create() or insertOne()"
echo "   - Ensure createdBy field references an admin user"
echo ""

echo "4. 🚀 Start Backend"
echo "   $ cd backend"
echo "   $ npm run dev"
echo "   Server should run on http://localhost:3000"
echo ""

echo "5. ⚛️ Start Frontend"
echo "   $ cd frontend"
echo "   $ npm run dev"
echo "   Frontend should run on http://localhost:5173"
echo ""

echo "6. 🧪 Test the Feature"
echo "   - Register/Login as student"
echo "   - Navigate to /student/tests"
echo "   - Click on any available test"
echo "   - Take the test and submit"
echo "   - View results"
echo ""

echo -e "${YELLOW}📱 Testing Workflow${NC}"
echo "===================="
echo ""
echo "Step 1: View Available Tests"
echo "  └─ Route: /student/tests"
echo "  └─ Displays all active tests as cards"
echo "  └─ Can filter by MCQ or Coding"
echo ""

echo "Step 2: Start a Test"
echo "  └─ Click 'Start Test' button"
echo "  └─ Creates a TestAttempt in database"
echo "  └─ Redirects to /student/test-attempt/:attemptId"
echo ""

echo "Step 3: Take Test"
echo "  └─ Timer starts counting down"
echo "  └─ For MCQ: Select answers from options"
echo "  └─ For Coding: Write code in editor"
echo "  └─ Answers auto-save every second"
echo "  └─ Navigate between questions"
echo ""

echo "Step 4: Submit Test"
echo "  └─ Click 'Submit' button or wait for timer"
echo "  └─ Answers are evaluated"
echo "  └─ Test attempt marked as completed"
echo "  └─ Redirects to /student/test-results/:attemptId"
echo ""

echo "Step 5: Review Results"
echo "  └─ See score and percentage"
echo "  └─ Pass/Fail status displayed"
echo "  └─ Can review all answers"
echo "  └─ For MCQ: See correct answers and explanations"
echo ""

echo -e "${YELLOW}🔧 Environment Variables${NC}"
echo "========================="
echo ""
echo "Backend (.env):"
echo "  MONGO_URI=mongodb://localhost:27017/recruitment-portal"
echo "  JWT_SECRET=your-secret-key"
echo "  FRONTEND_ORIGIN=http://localhost:5173"
echo ""

echo -e "${YELLOW}📊 File Structure${NC}"
echo "==================="
echo ""
echo "backend/server/"
echo "├── controllers/"
echo "│   └── testController.ts (UPDATED)"
echo "├── routes/"
echo "│   └── testRoutes.ts (UPDATED)"
echo "├── models/"
echo "│   ├── Test.ts (VERIFIED)"
echo "│   └── TestAttempt.ts (VERIFIED)"
echo ""
echo "frontend/src/"
echo "├── pages/"
echo "│   ├── StudentTests.tsx (NEW)"
echo "│   ├── TestAttempt.tsx (NEW)"
echo "│   └── TestResults.tsx (NEW)"
echo "├── components/"
echo "│   ├── TestCard.tsx (NEW)"
echo "│   └── QuestionCard.tsx (NEW)"
echo "└── services/"
echo "    └── testService.ts (NEW)"
echo ""

echo -e "${YELLOW}🔐 Security Features${NC}"
echo "===================="
echo ""
echo "✅ JWT Authentication required"
echo "✅ Role-based access (students only)"
echo "✅ Prevent cheating (refresh warnings, tab switch detection)"
echo "✅ Prevent retakes (once completed)"
echo "✅ Auto-submit on timer expiry"
echo "✅ Secure score calculation"
echo "✅ Input validation and sanitization"
echo ""

echo -e "${YELLOW}⚠️  Known Limitations (for future enhancement)${NC}"
echo "=============================================="
echo ""
echo "1. Coding test scoring is demo-based (50% for code submission)"
echo "   - Integrate code execution engine for real scoring"
echo ""
echo "2. No live proctoring implementation"
echo "   - Can integrate with browser proctoring APIs"
echo ""
echo "3. No plagiarism detection for coding"
echo "   - Implement MOSS or similar tool"
echo ""

echo -e "${YELLOW}📞 Deployment Checklist${NC}"
echo "======================="
echo ""
echo "Before deploying to production:"
echo ""
echo "[ ] Verify all test data"
echo "[ ] Test with multiple students simultaneously"
echo "[ ] Check timer accuracy"
echo "[ ] Verify auto-submit functionality"
echo "[ ] Test on different browsers"
echo "[ ] Test on mobile devices"
echo "[ ] Verify JWT token expiration handling"
echo "[ ] Check database indexes for performance"
echo "[ ] Enable CORS properly"
echo "[ ] Set up error monitoring (Sentry, etc.)"
echo "[ ] Configure CDN for static assets"
echo ""

echo -e "${GREEN}✨ Setup Complete!${NC}"
echo ""
echo "Next Steps:"
echo "1. Create test data in MongoDB"
echo "2. Start backend server"
echo "3. Start frontend development server"
echo "4. Test the feature end-to-end"
echo ""
echo "For detailed information, see: TESTS_IMPLEMENTATION_GUIDE.md"
